version: '3'

services:

    nginx:
        image: nginx:latest
        ports:
          - "8833:80"
          - "8833:443"
        volumes:
          - ./hosts:/etc/nginx/conf.d
          - ./www:/var/www
          - ./logs/nginx:/var/log/nginx
        links:
          - php
        restart: always
    php:
        build: ./images/php
        links:
          - mysql
        volumes:
          - ./www:/var/www
        restart: always
    mysql:
        image: mysql
        ports:
          - "3306:3306"
        restart: always
        volumes:
         - ./logs/mysql:/var/log/mysql
         - ./mysql:/var/lib/mysql
         - ./mysql-files:/var/lib/mysql-files
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: sait
    phpmyadmin:
        image: phpmyadmin
        restart: always
        links:
          - mysql
        ports:
          - 8080:80
        environment:
          PMA_HOST: mysql

